/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvsroot/pgmfi/asm662/src/asm/lex.yy.c,v 1.5 2003/07/11 01:15:39 a1k0n Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
static yyconst short int yy_accept[208] =
    {   0,
        0,    0,  130,  128,  125,  127,  128,    3,    3,  128,
      128,  128,  124,   11,  124,   12,  124,  124,  124,   64,
       74,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,   33,   34,   35,   36,   37,   38,   39,   40,    3,
        0,    1,    0,    0,  126,    4,    5,  124,  124,  124,
      124,  124,  124,  124,  124,    7,  124,  124,   13,    6,
      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
       75,   76,  124,   78,  124,  124,  124,  124,   85,  124,
      124,  124,   25,   26,   27,   28,   29,   30,   31,   32,
       89,   91,  124,   96,   98,  102,  104,  124,  124,  124,

      111,  124,  124,  124,  124,  124,   14,   15,  124,  124,
      124,    2,   41,   43,   45,   47,   48,   49,   51,   55,
       56,   57,   59,    9,   21,   22,   23,   24,  124,   62,
       65,   66,   67,   68,   69,   70,   71,   72,  124,   77,
       18,   79,   80,   82,   84,   10,   86,    8,  124,  124,
      124,   90,   92,   94,   97,   99,  101,  124,  105,  107,
      109,   17,  112,  113,  124,  117,   16,  124,  124,  124,
      122,   42,   44,   46,   50,   52,   53,   58,   60,  124,
       63,   73,   81,   83,   87,   19,   20,  124,   93,   95,
      100,  103,  106,  108,  110,  114,  115,  118,  119,  121,

      123,   54,   61,   88,  116,  120,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   13,    1,   14,   15,
        1,   16,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   17,   42,
        1,    1,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       17,   42,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    3,    2,    2,    2,
        2,    2,    2,    3,    4,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst short int yy_base[212] =
    {   0,
        0,    0,  242,  243,  243,  243,   38,   46,  200,  237,
      224,  222,    0,   39,  202,   43,   56,   42,  205,   62,
       60,   66,  203,   65,   67,  101,  120,  199,  197,  212,
       95,  243,  243,  243,  243,  243,  243,  243,  243,  190,
      205,  243,    0,  226,  243,  243,  243,    0,   42,  207,
      199,  197,  190,  191,   96,    0,  203,  183,    0,    0,
      183,  111,  183,  199,   87,  184,  106,  107,  195,  185,
        0,  196,  195,  178,  173,  182,  177,  186,  106,  175,
      167,  170,    0,    0,    0,    0,    0,    0,    0,    0,
      170,    0,  102,  178,  115,  185,    0,  173,  116,  168,

      181,  180,  180,  178,  163,  177,    0,    0,  169,  174,
      157,    0,  172,  171,  170,    0,    0,  169,  122,    0,
        0,  168,  167,    0,    0,    0,    0,    0,  154,  165,
        0,    0,    0,    0,    0,    0,    0,    0,  141,    0,
        0,    0,  163,  162,    0,    0,    0,    0,  144,   65,
      154,    0,  159,  158,    0,  157,    0,  146,  155,  154,
      153,    0,    0,  152,  136,    0,    0,  130,  130,  124,
      133,    0,    0,    0,    0,    0,  132,    0,    0,  127,
        0,    0,    0,    0,    0,    0,    0,  110,    0,    0,
        0,    0,    0,    0,    0,    0,  117,    0,  105,    0,

        0,    0,    0,    0,    0,    0,  243,  160,  163,  166,
       90
    } ;

static yyconst short int yy_def[212] =
    {   0,
      207,    1,  207,  207,  207,  207,  207,  207,    8,  208,
      207,  207,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  207,  207,  207,  207,  207,  207,  207,  207,    8,
      210,  207,  211,  208,  207,  207,  207,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  211,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209,  209,  209,  209,  209,  209,    0,  207,  207,  207,
      207
    } ;

static yyconst short int yy_nxt[286] =
    {   0,
        4,    5,    6,    7,    8,    9,    9,    9,    9,    9,
        9,    9,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   13,   13,   13,   19,   20,   13,   21,   22,
       23,   24,   25,   13,   26,   27,   28,   29,   30,   13,
       31,   13,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   49,
       52,  113,  114,   41,   41,   41,   41,   41,   41,   50,
       42,   53,   54,   55,   56,   61,   62,   57,   71,   72,
       65,   58,   63,   66,   74,   67,   43,   78,   59,  186,
       68,  112,   69,  187,   73,   60,   70,   75,   80,   79,

      107,  108,   81,   76,   82,   83,   84,   85,   86,   87,
       88,   89,   90,  120,  109,  125,  126,  127,  128,   91,
       92,  131,  132,  206,  147,  110,  111,  134,  136,  148,
      153,  121,   93,  160,  156,  205,  154,   94,   95,   96,
      176,  177,  135,  137,  161,  204,   97,  203,   98,  157,
      202,  201,  200,  199,   99,  100,  101,  102,  198,  103,
       44,   44,   44,   44,   48,   48,   48,   41,  197,   41,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  185,
      184,  183,  182,  181,  180,  179,  178,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,

      162,  159,  158,  155,  152,  151,  150,  149,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  133,  130,  129,
      124,  123,  122,  119,  118,  117,  116,  115,   45,   42,
      207,  106,  105,  104,   77,   64,   51,   47,   46,   45,
      207,  207,    3,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207
    } ;

static yyconst short int yy_chk[286] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    7,    7,    7,    7,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   14,
       16,   49,   49,    8,    8,    8,    8,    8,    8,   14,
        8,   16,   16,   17,   17,   18,   18,   17,   21,   21,
       20,   17,   18,   20,   22,   20,    8,   24,   17,  150,
       20,  211,   20,  150,   21,   17,   20,   22,   25,   24,

       31,   31,   25,   22,   25,   26,   26,   26,   26,   26,
       26,   26,   26,   55,   31,   62,   62,   62,   62,   26,
       26,   65,   65,  199,   79,   31,   31,   67,   68,   79,
       93,   55,   26,   99,   95,  197,   93,   26,   27,   27,
      119,  119,   67,   68,   99,  188,   27,  180,   27,   95,
      177,  171,  170,  169,   27,   27,   27,   27,  168,   27,
      208,  208,  208,  208,  209,  209,  209,  210,  165,  210,
      164,  161,  160,  159,  158,  156,  154,  153,  151,  149,
      144,  143,  139,  130,  129,  123,  122,  118,  115,  114,
      113,  111,  110,  109,  106,  105,  104,  103,  102,  101,

      100,   98,   96,   94,   91,   82,   81,   80,   78,   77,
       76,   75,   74,   73,   72,   70,   69,   66,   64,   63,
       61,   58,   57,   54,   53,   52,   51,   50,   44,   41,
       40,   30,   29,   28,   23,   19,   15,   12,   11,   10,
        9,    3,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "asm662.l"
#define INITIAL 0
#line 2 "asm662.l"
/* build with lex -i */
#include "y.tab.h"
#include "asm662.h"
#line 500 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 7 "asm662.l"


#line 654 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 208 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 243 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "asm662.l"
{ sscanf(yytext, "%xh", &yylval.value);  return NUMBER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 "asm662.l"
{ sscanf(yytext+2, "%x", &yylval.value); return NUMBER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "asm662.l"
{ yylval.value = atoi(yytext); return NUMBER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 "asm662.l"
return SHIFTL;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 "asm662.l"
return SHIFTR;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 "asm662.l"
return DW;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "asm662.l"
return DB;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 "asm662.l"
return ORG;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 "asm662.l"
return EQU;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 "asm662.l"
return OFFSET;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 "asm662.l"
return R_A;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 "asm662.l"
return R_C;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "asm662.l"
return R_DP;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 22 "asm662.l"
return R_X1;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 23 "asm662.l"
return R_X2;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 24 "asm662.l"
return R_USP;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 25 "asm662.l"
return R_SSP;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 26 "asm662.l"
return R_LRB;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 27 "asm662.l"
return R_PSWH;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 28 "asm662.l"
return R_PSWL;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 29 "asm662.l"
return R_er0;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 30 "asm662.l"
return R_er1;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 31 "asm662.l"
return R_er2;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 32 "asm662.l"
return R_er3;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 33 "asm662.l"
return R_r0;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 34 "asm662.l"
return R_r1;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 35 "asm662.l"
return R_r2;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 36 "asm662.l"
return R_r3;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 37 "asm662.l"
return R_r4;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 38 "asm662.l"
return R_r5;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 39 "asm662.l"
return R_r6;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 40 "asm662.l"
return R_r7;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 41 "asm662.l"
return DOT0;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 42 "asm662.l"
return DOT1;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 43 "asm662.l"
return DOT2;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 44 "asm662.l"
return DOT3;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 45 "asm662.l"
return DOT4;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 46 "asm662.l"
return DOT5;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 47 "asm662.l"
return DOT6;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 48 "asm662.l"
return DOT7;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 50 "asm662.l"
return ADC;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 51 "asm662.l"
return ADCB;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 52 "asm662.l"
return ADD;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 53 "asm662.l"
return ADDB;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 54 "asm662.l"
return AND;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 55 "asm662.l"
return ANDB;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 56 "asm662.l"
return BRK;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 57 "asm662.l"
return CAL;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 58 "asm662.l"
return CLR;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 59 "asm662.l"
return CLRB;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 60 "asm662.l"
return CMP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 61 "asm662.l"
return CMPB;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 62 "asm662.l"
return CMPC;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 63 "asm662.l"
return CMPCB;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 64 "asm662.l"
return DAA;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 65 "asm662.l"
return DAS;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 66 "asm662.l"
return DEC;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 67 "asm662.l"
return DECB;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 68 "asm662.l"
return DIV;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 69 "asm662.l"
return DIVB;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 70 "asm662.l"
return EXTND;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 71 "asm662.l"
return INC;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 72 "asm662.l"
return INCB;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 73 "asm662.l"
return J;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 74 "asm662.l"
return JBR;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 75 "asm662.l"
return JBS;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 76 "asm662.l"
return JEQ;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 77 "asm662.l"
return JGE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 78 "asm662.l"
return JGT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 79 "asm662.l"
return JLE;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 80 "asm662.l"
return JLT;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 81 "asm662.l"
return JNE;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 82 "asm662.l"
return JRNZ;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 83 "asm662.l"
return L;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 84 "asm662.l"
return LB;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 85 "asm662.l"
return LC;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 86 "asm662.l"
return LCB;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 87 "asm662.l"
return MB;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 88 "asm662.l"
return MBR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 89 "asm662.l"
return MOV;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 90 "asm662.l"
return MOVB;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 91 "asm662.l"
return MUL;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 92 "asm662.l"
return MULB;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 93 "asm662.l"
return NOP;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 94 "asm662.l"
return OR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 95 "asm662.l"
return ORB;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 96 "asm662.l"
return POPS;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 97 "asm662.l"
return PUSHS;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 98 "asm662.l"
return RB;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 99 "asm662.l"
return RBR;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 100 "asm662.l"
return RC;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 101 "asm662.l"
return ROL;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 102 "asm662.l"
return ROLB;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 103 "asm662.l"
return ROR;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 104 "asm662.l"
return RORB;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 105 "asm662.l"
return RT;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 106 "asm662.l"
return RTI;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 107 "asm662.l"
return SB;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 108 "asm662.l"
return SBC;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 109 "asm662.l"
return SBCB;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 110 "asm662.l"
return SBR;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 111 "asm662.l"
return SC;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 112 "asm662.l"
return SCAL;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 113 "asm662.l"
return SJ;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 114 "asm662.l"
return SLL;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 115 "asm662.l"
return SLLB;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 116 "asm662.l"
return SRA;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 117 "asm662.l"
return SRAB;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 118 "asm662.l"
return SRL;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 119 "asm662.l"
return SRLB;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 120 "asm662.l"
return ST;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 121 "asm662.l"
return STB;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 122 "asm662.l"
return SUB;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 123 "asm662.l"
return SUBB;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 124 "asm662.l"
return SWAP;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 125 "asm662.l"
return SWAPB;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 126 "asm662.l"
return TRB;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 127 "asm662.l"
return VCAL;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 128 "asm662.l"
return XCHG;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 129 "asm662.l"
return XCHGB;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 130 "asm662.l"
return XNBL;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 131 "asm662.l"
return XOR;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 132 "asm662.l"
return XORB;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 133 "asm662.l"
{ yylval.sym = get_symbol(yytext); return SYMBOL; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 134 "asm662.l"
;
	YY_BREAK
case 126:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 135 "asm662.l"
;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 136 "asm662.l"
{ lineno++; return NL; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 137 "asm662.l"
return yytext[0];
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 139 "asm662.l"
ECHO;
	YY_BREAK
#line 1385 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 208 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 208 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 207);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 139 "asm662.l"


